# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 1280)
        MainWindow.setStyleSheet("/* Closed (default) QComboBox view */\n"
"QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"    min-width: 120px;\n"
"    min-height: 30px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Drop-down arrow */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"    background-color: #f0742f;\n"
"    border-left: 1px solid #888;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"\n"
"/* Drop-down list (popup) */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #5c55e9;  /* Popup background */\n"
"    color: white;               /* Popup text */\n"
"    selection-background-color: #3d4ef2;\n"
"    selection-color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"QComboBox {\n"
"    background-color: #292f45;\n"
"    color: #ffffff;\n"
"    border: 1px solid #f0742f;\n"
"    padding-right: 20px;      /* make room for the arrow */\n"
"}\n"
"\n"
"/* drop-down “button” area */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid #f0742f;\n"
"}\n"
"\n"
"/* hide any default icon */\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    /* zero-size box so borders form the triangle */\n"
"    width: 0;\n"
"    height: 0;\n"
"    /* left and right edges transparent */\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    /* top edge colored → points down */\n"
"    border-top: 7px solid white;\n"
"}\n"
"\n"
"/* when pressed, you can nudge it if you like */\n"
"QComboBox::down-arrow:on {\n"
"    border-top-color: lightgray;  /* optional press effect */\n"
"    margin-top: 2px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    background: transparent;\n"
"    width: 0;\n"
"    height: 0;\n"
"    border-left: 5px solid transparent;\n"
"    border-right:5px solid transparent;\n"
"    border-top: 5px solid white;    /* ← this is your white arrow */\n"
"}\n"
"/*Copyright (c) DevSec Studio. All rights reserved.\n"
"\n"
"MIT License\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
"*/\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: #292f45;\n"
"    color: #b9b9bb;\n"
"    border-color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: #292f45;\n"
"    color: #b9b9bb;\n"
"    border-color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: #f0742f;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 17px;\n"
"    border-color: #f0742f;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #fc7c11;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #ff6b35;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton\n"
"{\n"
"    background-color: #292f45;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::hover\n"
"{\n"
"    background-color: #fc7c11;\n"
"    color: #000000;\n"
"    padding: 2px;\n"
"    border-radius: 15px;\n"
"    border-color: #fc7c11;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::pressed\n"
"{\n"
"    background-color: #fc7c11;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit{\n"
"    background-color: #292f45;\n"
"    color: #b9b9bb;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top: 0px;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"    border-color: #b9b9bb;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: #b9b9bb;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #00111d;\n"
"    border: 1px solid #f0742f;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(\"./ressources/check.png\"); /*To replace*/\n"
"    background-color: #1f2b2b;\n"
"    border: 1px solid #f0742f;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #f0742f;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 90, 681, 321))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(70, 40, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(270, 40, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(270, 140, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(70, 140, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.comboBox_14 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_14.setGeometry(QtCore.QRect(260, 60, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_14.setFont(font)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_13 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_13.setGeometry(QtCore.QRect(260, 160, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_13.setFont(font)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_12 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_12.setGeometry(QtCore.QRect(60, 60, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_12.setFont(font)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_7.setGeometry(QtCore.QRect(60, 160, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_22 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_22.setGeometry(QtCore.QRect(470, 60, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_22.setFont(font)
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(270, 230, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(480, 40, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(70, 230, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.comboBox_23 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_23.setGeometry(QtCore.QRect(60, 250, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_23.setFont(font)
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_24 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_24.setGeometry(QtCore.QRect(470, 160, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_24.setFont(font)
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_25 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_25.setGeometry(QtCore.QRect(260, 250, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_25.setFont(font)
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(480, 140, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 430, 681, 221))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(80, 40, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(500, 40, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(80, 130, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(280, 40, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.comboBox_20 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_20.setGeometry(QtCore.QRect(60, 60, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_20.setFont(font)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(280, 130, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(490, 130, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.comboBox_21 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_21.setGeometry(QtCore.QRect(260, 60, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_21.setFont(font)
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_26 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_26.setGeometry(QtCore.QRect(480, 60, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_26.setFont(font)
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_27 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_27.setGeometry(QtCore.QRect(260, 150, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_27.setFont(font)
        self.comboBox_27.setObjectName("comboBox_27")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_30 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_30.setGeometry(QtCore.QRect(480, 150, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_30.setFont(font)
        self.comboBox_30.setObjectName("comboBox_30")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_31 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_31.setGeometry(QtCore.QRect(60, 150, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_31.setFont(font)
        self.comboBox_31.setObjectName("comboBox_31")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 670, 681, 151))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(140, 40, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(340, 40, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.comboBox_28 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_28.setGeometry(QtCore.QRect(140, 60, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_28.setFont(font)
        self.comboBox_28.setObjectName("comboBox_28")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_29 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_29.setGeometry(QtCore.QRect(340, 60, 147, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_29.setFont(font)
        self.comboBox_29.setObjectName("comboBox_29")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 10, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    min-width: 100px;    /* Optional: Width */\n"
"    min-height: 30px;    /* Optional: Height */\n"
"    font-size: 34px;     /* Adjust font size */\n"
"    font-weight: bold;   /* Optional: make text bold */\n"
"}")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 10, 141, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Users/nikhi/Downloads/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionload = QtWidgets.QAction(MainWindow)
        self.actionload.setObjectName("actionload")
        self.menufile.addAction(self.actionsave)
        self.menufile.addAction(self.actionload)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Digital Inputs "))
        self.label.setText(_translate("MainWindow", "Logic Input 1 "))
        self.label_2.setText(_translate("MainWindow", "Logic Input 2"))
        self.label_7.setText(_translate("MainWindow", "Logic Input 6"))
        self.label_8.setText(_translate("MainWindow", "Logic Input 5"))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_14.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_14.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_14.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_14.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_14.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_14.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_14.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_13.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_13.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_13.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_13.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_13.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_13.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_13.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_12.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_12.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_12.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_12.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_12.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_12.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_7.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_22.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_22.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_22.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_22.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_22.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_22.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_22.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_22.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_22.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.label_17.setText(_translate("MainWindow", "Logic Input 4"))
        self.label_18.setText(_translate("MainWindow", "Logic Input 3"))
        self.label_19.setText(_translate("MainWindow", "Logic Input 8"))
        self.comboBox_23.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_23.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_23.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_23.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_23.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_23.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_23.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_23.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_23.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_24.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_24.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_24.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_24.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_24.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_24.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_24.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_24.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_24.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_25.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_25.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_25.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_25.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_25.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_25.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_25.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_25.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_25.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.label_20.setText(_translate("MainWindow", "Logic Input 7"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Analog inputs "))
        self.label_9.setText(_translate("MainWindow", "Analog Input 1 "))
        self.label_10.setText(_translate("MainWindow", "Analog Input 2"))
        self.label_15.setText(_translate("MainWindow", "Analog Input 4"))
        self.label_16.setText(_translate("MainWindow", "Analog Input 3"))
        self.comboBox_20.setItemText(0, _translate("MainWindow", "BIN"))
        self.comboBox_20.setItemText(1, _translate("MainWindow", "NTC"))
        self.label_21.setText(_translate("MainWindow", "Analog Input 4"))
        self.label_23.setText(_translate("MainWindow", "Analog Input 4"))
        self.comboBox_21.setItemText(0, _translate("MainWindow", "BIN"))
        self.comboBox_21.setItemText(1, _translate("MainWindow", "NTC"))
        self.comboBox_26.setItemText(0, _translate("MainWindow", "BIN"))
        self.comboBox_26.setItemText(1, _translate("MainWindow", "NTC"))
        self.comboBox_27.setItemText(0, _translate("MainWindow", "BIN"))
        self.comboBox_27.setItemText(1, _translate("MainWindow", "NTC"))
        self.comboBox_30.setItemText(0, _translate("MainWindow", "BIN"))
        self.comboBox_30.setItemText(1, _translate("MainWindow", "NTC"))
        self.comboBox_31.setItemText(0, _translate("MainWindow", "BIN"))
        self.comboBox_31.setItemText(1, _translate("MainWindow", "NTC"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Project Details"))
        self.label_11.setText(_translate("MainWindow", "MLD Typs"))
        self.label_22.setText(_translate("MainWindow", "Lamp Type"))
        self.comboBox_28.setItemText(0, _translate("MainWindow", "MINI"))
        self.comboBox_28.setItemText(1, _translate("MainWindow", "STD"))
        self.comboBox_28.setItemText(2, _translate("MainWindow", "PLUS"))
        self.comboBox_29.setItemText(0, _translate("MainWindow", "Tail Lamp"))
        self.comboBox_29.setItemText(1, _translate("MainWindow", "Head Lamp"))
        self.comboBox_29.setItemText(2, _translate("MainWindow", "Car Body"))
        self.label_4.setText(_translate("MainWindow", "Test App "))
        self.pushButton.setText(_translate("MainWindow", "Start Test"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionload.setText(_translate("MainWindow", "load"))
