# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(567, 416)
        MainWindow.setStyleSheet("/*Copyright (c) DevSec Studio. All rights reserved.\n"
"\n"
"MIT License\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
"*/\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: #fff;\n"
"    color: red;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #454544;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: #5c55e9;\n"
"    color: #fff;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border-top-right-radius: 15px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 15px;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #5c5c5c;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #5564f2;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3d4ef2;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: #5c55e9;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox::indicator\n"
"{\n"
"    background-color: #323232;\n"
"    border: 1px solid darkgray;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(\"./ressources/check.png\");\n"
"    background-color: #5c55e9;\n"
"    border: 1px solid #5c55e9;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #5c55e9;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"    background-color: #c2c7d5;\n"
"    color: #2a547f;\n"
"    border: none;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QListView-----*/\n"
"QListView\n"
"{\n"
"    background-color: #5c55e9;\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    show-decoration-selected: 0;\n"
"    border-radius: 4px;\n"
"    padding-left: -15px;\n"
"    padding-right: -15px;\n"
"    padding-top: 5px;\n"
"\n"
"} \n"
"\n"
"\n"
"QListView:disabled \n"
"{\n"
"    background-color: #5c5c5c;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item\n"
"{\n"
"    background-color: #454e5e;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    border-radius: 0px;\n"
"    padding-left : 10px;\n"
"    height: 32px;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected\n"
"{\n"
"    color: #000;\n"
"    background-color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:!selected\n"
"{\n"
"    color:white;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding-left : 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:!selected:hover\n"
"{\n"
"    color: #fff;\n"
"    background-color: #5564f2;\n"
"    border: none;\n"
"    padding-left : 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeView-----*/\n"
"QTreeView \n"
"{\n"
"    background-color: #fff;\n"
"    show-decoration-selected: 0;\n"
"    color: #454544;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView:disabled\n"
"{\n"
"    background-color: #242526;\n"
"    show-decoration-selected: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item \n"
"{\n"
"    border-top-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:hover \n"
"{\n"
"    background-color: #bcbdbb;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:selected \n"
"{\n"
"    background-color: #5c55e9;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:selected:active\n"
"{\n"
"    background-color: #5c55e9;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:selected:disabled\n"
"{\n"
"    background-color: #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings \n"
"{\n"
"    image: url(://tree-closed.png);\n"
"\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  \n"
"{\n"
"    image: url(://tree-open.png);\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTableView & QTableWidget-----*/\n"
"QTableView\n"
"{\n"
"    background-color: #fff;\n"
"    border: 1px solid gray;\n"
"    color: #454544;\n"
"    gridline-color: gray;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::disabled\n"
"{\n"
"    background-color: #242526;\n"
"    border: 1px solid #32414B;\n"
"    color: #656565;\n"
"    gridline-color: #656565;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:hover \n"
"{\n"
"    background-color: #bcbdbb;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:selected \n"
"{\n"
"    background-color: #5c55e9;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:selected:disabled\n"
"{\n"
"    background-color: #1a1b1c;\n"
"    border: 2px solid #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"    background-color: #ced5e3;\n"
"    border: none;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    color: #2a547f;\n"
"    border: 0px;\n"
"    background-color: #ced5e3;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:disabled\n"
"{\n"
"    background-color: #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"{\n"
"    color: #fff;\n"
"    background-color: #5c55e9;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked:disabled\n"
"{\n"
"    color: #656565;\n"
"    background-color: #525251;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one\n"
"{\n"
"    border-top: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"{\n"
"    border-top: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"QHeaderView::section::horizontal::only-one\n"
"{\n"
"    border-left: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"{\n"
"    border-left: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal \n"
"{\n"
"    background-color: transparent;\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"    border: none;\n"
"    min-width: 100px;\n"
"    background-color: #7e92b7;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal, \n"
"QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-page:horizontal, \n"
"QScrollBar::sub-page:horizontal \n"
"{\n"
"    width: 0px;\n"
"    background-color: #d8dce6;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical \n"
"{\n"
"    background-color: transparent;\n"
"    width: 8px;\n"
"    margin: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"    border: none;\n"
"    min-height: 100px;\n"
"    background-color: #7e92b7;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical \n"
"{\n"
"    height: 0px;\n"
"    background-color: #d8dce6;\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 241, 261))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(140, 30, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(140, 90, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(30, 90, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.comboBox_14 = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_14.setGeometry(QtCore.QRect(140, 50, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.comboBox_14.setFont(font)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_13 = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_13.setGeometry(QtCore.QRect(140, 110, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.comboBox_13.setFont(font)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_12 = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_12.setGeometry(QtCore.QRect(30, 50, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.comboBox_12.setFont(font)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_7.setGeometry(QtCore.QRect(30, 110, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_22 = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_22.setGeometry(QtCore.QRect(30, 160, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.comboBox_22.setFont(font)
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.label_17 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(140, 140, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(30, 140, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(140, 200, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.comboBox_23 = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_23.setGeometry(QtCore.QRect(140, 220, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.comboBox_23.setFont(font)
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_24 = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_24.setGeometry(QtCore.QRect(30, 220, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.comboBox_24.setFont(font)
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_25 = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_25.setGeometry(QtCore.QRect(140, 160, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.comboBox_25.setFont(font)
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.label_20 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(30, 200, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 30, 131, 251))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(30, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(30, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(30, 190, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(30, 80, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.comboBox_18 = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBox_18.setGeometry(QtCore.QRect(30, 150, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.comboBox_18.setFont(font)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_19 = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBox_19.setGeometry(QtCore.QRect(30, 210, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.comboBox_19.setFont(font)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_20 = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBox_20.setGeometry(QtCore.QRect(30, 50, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.comboBox_20.setFont(font)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_21 = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBox_21.setGeometry(QtCore.QRect(30, 100, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.comboBox_21.setFont(font)
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(420, 130, 131, 151))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(30, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_22 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(30, 80, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.comboBox_28 = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.comboBox_28.setGeometry(QtCore.QRect(30, 50, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.comboBox_28.setFont(font)
        self.comboBox_28.setObjectName("comboBox_28")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_28.addItem("")
        self.comboBox_29 = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.comboBox_29.setGeometry(QtCore.QRect(30, 100, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        self.comboBox_29.setFont(font)
        self.comboBox_29.setObjectName("comboBox_29")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 50, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QWidget {\n"
"    background-image: url(:/images/bg.jpg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Users/nikhi/Downloads/Untitled.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 300, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Users/nikhi/Downloads/play.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 567, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(parent=self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.actionsave = QtGui.QAction(parent=MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionload = QtGui.QAction(parent=MainWindow)
        self.actionload.setObjectName("actionload")
        self.menufile.addAction(self.actionsave)
        self.menufile.addAction(self.actionload)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Digital Inputs "))
        self.label.setText(_translate("MainWindow", "Logic Input 1 "))
        self.label_2.setText(_translate("MainWindow", "Logic Input 2"))
        self.label_7.setText(_translate("MainWindow", "Logic Input 6"))
        self.label_8.setText(_translate("MainWindow", "Logic Input 5"))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_14.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_14.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_14.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_14.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_14.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_14.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_14.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_13.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_13.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_13.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_13.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_13.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_13.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_13.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_12.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_12.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_12.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_12.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_12.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_12.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_7.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_22.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_22.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_22.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_22.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_22.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_22.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_22.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_22.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_22.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.label_17.setText(_translate("MainWindow", "Logic Input 4"))
        self.label_18.setText(_translate("MainWindow", "Logic Input 3"))
        self.label_19.setText(_translate("MainWindow", "Logic Input 8"))
        self.comboBox_23.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_23.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_23.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_23.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_23.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_23.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_23.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_23.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_23.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_24.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_24.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_24.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_24.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_24.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_24.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_24.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_24.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_24.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_25.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_25.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_25.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_25.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_25.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_25.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_25.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_25.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_25.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.label_20.setText(_translate("MainWindow", "Logic Input 7"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Analog inputs "))
        self.label_9.setText(_translate("MainWindow", "Analog Input 1 "))
        self.label_10.setText(_translate("MainWindow", "Analog Input 2"))
        self.label_15.setText(_translate("MainWindow", "Analog Input 4"))
        self.label_16.setText(_translate("MainWindow", "Analog Input 3"))
        self.comboBox_18.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_18.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_18.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_18.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_18.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_18.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_18.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_18.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_18.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_19.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_19.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_19.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_19.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_19.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_19.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_19.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_19.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_19.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_20.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_20.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_20.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_20.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_20.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_20.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_20.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_20.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_20.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.comboBox_21.setItemText(0, _translate("MainWindow", "LB"))
        self.comboBox_21.setItemText(1, _translate("MainWindow", "HB"))
        self.comboBox_21.setItemText(2, _translate("MainWindow", "DRL/POL"))
        self.comboBox_21.setItemText(3, _translate("MainWindow", "TI"))
        self.comboBox_21.setItemText(4, _translate("MainWindow", "Animation"))
        self.comboBox_21.setItemText(5, _translate("MainWindow", "Stop"))
        self.comboBox_21.setItemText(6, _translate("MainWindow", "Tail"))
        self.comboBox_21.setItemText(7, _translate("MainWindow", "Side Marker"))
        self.comboBox_21.setItemText(8, _translate("MainWindow", "Seq TI"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Project Details"))
        self.label_11.setText(_translate("MainWindow", "MLD Typs"))
        self.label_22.setText(_translate("MainWindow", "Lamp Type"))
        self.comboBox_28.setItemText(0, _translate("MainWindow", "MINI"))
        self.comboBox_28.setItemText(1, _translate("MainWindow", "STD"))
        self.comboBox_28.setItemText(2, _translate("MainWindow", "PLUS"))
        self.comboBox_29.setItemText(0, _translate("MainWindow", "Tail Lamp"))
        self.comboBox_29.setItemText(1, _translate("MainWindow", "Head Lamp"))
        self.comboBox_29.setItemText(2, _translate("MainWindow", "Car Body"))
        self.pushButton.setText(_translate("MainWindow", "Start Test"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionload.setText(_translate("MainWindow", "load"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
